export {
  deleteUserProfile,
  filterMarketingOptedInUserIds,
  getConversationHistory,
  getEscalationState,
  getUserLanguage,
  getUserProfile,
  markConsentNoticeShown,
  markUserFirstContact,
  recordChatFeedback,
  saveConversationMessage,
  setEscalationState,
  setLastActionOtpAt,
  setMarketingOptIn,
  setUserLanguage,
  setUserOdooPartner,
  setUserOdooVerificationStatus,
  setSalesSessionExpiresAt,
  setUserPendingFlow,
  setLastProductContext,
  setLastQuoteListFrom,
  setUserRole,
  updateUserScore,
} from '../firestore';
export type { PendingFlowState, UserLanguage, UserProfile, UserRole } from './types';
