export {
  addSaleOrderLine,
  cancelSaleOrder,
  confirmSaleOrder,
  createInvoiceForSaleOrder,
  createQuotationFromLine,
  findOrderByReference,
  findPaymentTermByName,
  listPaymentTerms,
  pickDefaultPaymentTermName,
  getDefaultPaymentTermName,
  findSaleOrderLineByProduct,
  getSaleOrderById,
  getSaleOrderPdfLink,
  getSaleOrderPortalLink,
  getSaleOrdersForPartner,
  markSaleOrderSent,
  sendQuotationEmail,
  removeSaleOrderLine,
  updateSaleOrderLineQty,
} from '../odoo';
export type { OdooSaleOrder, OdooSaleOrderLine } from './types';
